/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface EmpArticleMolecule {
    'productImage': string;
  }
  interface EmpButtonMolecule {
    'center': boolean;
    'full': boolean;
    'kind': string & 'primary' | 'gray';
  }
  interface EmpFooterMolecule {}
  interface EmpIMolecule {
    'hover': boolean;
    'icon': string;
    'pointer': boolean;
  }
  interface FlApp {}
  interface HomePage {}
}

declare global {


  interface HTMLEmpArticleMoleculeElement extends Components.EmpArticleMolecule, HTMLStencilElement {}
  var HTMLEmpArticleMoleculeElement: {
    prototype: HTMLEmpArticleMoleculeElement;
    new (): HTMLEmpArticleMoleculeElement;
  };

  interface HTMLEmpButtonMoleculeElement extends Components.EmpButtonMolecule, HTMLStencilElement {}
  var HTMLEmpButtonMoleculeElement: {
    prototype: HTMLEmpButtonMoleculeElement;
    new (): HTMLEmpButtonMoleculeElement;
  };

  interface HTMLEmpFooterMoleculeElement extends Components.EmpFooterMolecule, HTMLStencilElement {}
  var HTMLEmpFooterMoleculeElement: {
    prototype: HTMLEmpFooterMoleculeElement;
    new (): HTMLEmpFooterMoleculeElement;
  };

  interface HTMLEmpIMoleculeElement extends Components.EmpIMolecule, HTMLStencilElement {}
  var HTMLEmpIMoleculeElement: {
    prototype: HTMLEmpIMoleculeElement;
    new (): HTMLEmpIMoleculeElement;
  };

  interface HTMLFlAppElement extends Components.FlApp, HTMLStencilElement {}
  var HTMLFlAppElement: {
    prototype: HTMLFlAppElement;
    new (): HTMLFlAppElement;
  };

  interface HTMLHomePageElement extends Components.HomePage, HTMLStencilElement {}
  var HTMLHomePageElement: {
    prototype: HTMLHomePageElement;
    new (): HTMLHomePageElement;
  };
  interface HTMLElementTagNameMap {
    'emp-article-molecule': HTMLEmpArticleMoleculeElement;
    'emp-button-molecule': HTMLEmpButtonMoleculeElement;
    'emp-footer-molecule': HTMLEmpFooterMoleculeElement;
    'emp-i-molecule': HTMLEmpIMoleculeElement;
    'fl-app': HTMLFlAppElement;
    'home-page': HTMLHomePageElement;
  }
}

declare namespace LocalJSX {
  interface EmpArticleMolecule {
    'onImageClick'?: (event: CustomEvent<void>) => void;
    'productImage'?: string;
  }
  interface EmpButtonMolecule {
    'center'?: boolean;
    'full'?: boolean;
    'kind'?: string & 'primary' | 'gray';
  }
  interface EmpFooterMolecule {}
  interface EmpIMolecule {
    'hover'?: boolean;
    'icon'?: string;
    'pointer'?: boolean;
  }
  interface FlApp {}
  interface HomePage {}

  interface IntrinsicElements {
    'emp-article-molecule': EmpArticleMolecule;
    'emp-button-molecule': EmpButtonMolecule;
    'emp-footer-molecule': EmpFooterMolecule;
    'emp-i-molecule': EmpIMolecule;
    'fl-app': FlApp;
    'home-page': HomePage;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'emp-article-molecule': LocalJSX.EmpArticleMolecule & JSXBase.HTMLAttributes<HTMLEmpArticleMoleculeElement>;
      'emp-button-molecule': LocalJSX.EmpButtonMolecule & JSXBase.HTMLAttributes<HTMLEmpButtonMoleculeElement>;
      'emp-footer-molecule': LocalJSX.EmpFooterMolecule & JSXBase.HTMLAttributes<HTMLEmpFooterMoleculeElement>;
      'emp-i-molecule': LocalJSX.EmpIMolecule & JSXBase.HTMLAttributes<HTMLEmpIMoleculeElement>;
      'fl-app': LocalJSX.FlApp & JSXBase.HTMLAttributes<HTMLFlAppElement>;
      'home-page': LocalJSX.HomePage & JSXBase.HTMLAttributes<HTMLHomePageElement>;
    }
  }
}


